server:
  port: 8085 # 임의 설정

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL:jdbc:mariadb://localhost:3306/don-forget}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 이메일 설정 (추후 구현시)
# mail:
#   host: smtp.gmail.com
