spring:
  application:
    name: payment-service
  
  # 1. 설정 서버 없어도 서버가 뜨게끔 설정 (중요!)
  cloud:
    config:
      enabled: false 
  
  # 2. DB 정보 (아까 Payment와 똑같이 3307 / user_bill / 1234!)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/user_bill
    username: root
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true

server:
  port: 8082 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/