spring:
  application:
    name: eureka-server

# http://localhost:8761/ 에서 Eureka 서버가 실행됩니다.(eureka에 등록된 서비스들을 확인할 수 있습니다.)
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # Eureka 서버에 자신을 등록하지 않도록 설정
    fetch-registry: false   # Eureka 서버에서 다른 서비스의 정보를 가져오지 않도록 설정 
