spring:
  application:
    name: external-billing-service
  
  # 설정 서버 의존성을 완전히 무시하고 로컬 설정 사용
  cloud:
    config:
      enabled: false 
  
  # DB 정보 (소정님 3307 / user_bill / 1234 맞춤)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/user_bill
    username: root
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083  # 여기서 포트 번호 8081로 고정!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/