server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          default-label: ${CONFIG_GIT_BRANCH:main}
          clone-on-start: true


    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health