server:
    port: 8888
spring:
  application:
    name: configserver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  

  cloud:
    config:
      server:

        git:

          uri: https://github.com/lgcns-mini2nd-team3/don-forget-config.git

          clone-on-start: true

          default-label: feature/payment-service
    

    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health